# Generated by Django 6.0.4 on 2026-05-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paletas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paletas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_paletas'),
        ),
    ]
