# Generated by Django 6.0.4 on 2026-05-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paletas', '0002_paletas_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paletas',
            new_name='Paleta',
        ),
    ]
