# Generated by Django 6.0.4 on 2026-05-05 23:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_mensajes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensajes',
            new_name='Mensaje',
        ),
    ]
